<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="46428" started-at="2018-02-19T12:23:20Z" finished-at="2018-02-19T12:24:07Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="46428" started-at="2018-02-19T12:23:20Z" finished-at="2018-02-19T12:24:07Z">
      <class name="Tests.HomePage_Test">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:Tests.HomePage_Test@6500df86]" name="beforeSuite" is-config="true" duration-ms="1516" started-at="2018-02-19T17:53:19Z" finished-at="2018-02-19T17:53:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:Tests.HomePage_Test@6500df86]" name="beforeTest" is-config="true" duration-ms="3311" started-at="2018-02-19T17:53:20Z" finished-at="2018-02-19T17:53:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforClass()[pri:0, instance:Tests.HomePage_Test@6500df86]" name="beforClass" is-config="true" duration-ms="42748" started-at="2018-02-19T17:53:23Z" finished-at="2018-02-19T17:54:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforClass -->
        <test-method status="SKIP" signature="HomePageValidation(java.lang.String)[pri:0, instance:Tests.HomePage_Test@6500df86]" name="HomePageValidation" duration-ms="0" started-at="2018-02-19T17:54:07Z" data-provider="dataProvider" finished-at="2018-02-19T17:54:07Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:115)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:509)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1308)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1036)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1126)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException
	at Tests.BaseTest.dataProvider(BaseTest.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:55)
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
	... 22 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HomePageValidation -->
        <test-method status="PASS" signature="aftersuite()[pri:0, instance:Tests.HomePage_Test@6500df86]" name="aftersuite" is-config="true" duration-ms="7549" started-at="2018-02-19T17:54:07Z" finished-at="2018-02-19T17:54:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftersuite -->
      </class> <!-- Tests.HomePage_Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
